Add source generator and example project

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,6 +7,7 @@ on:
   pull_request:
     branches:
       - main
+      - feature/*
 
 env:
   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
@@ -40,3 +41,20 @@ jobs:
 
       - name: Build
         run: dotnet build -c Release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }}
+
+      - name: Test
+        continue-on-error: true
+        run: dotnet test -c Release --logger trx
+
+      - name: Process test reports
+        id: process-trx
+        if: always()
+        uses: im-open/process-dotnet-test-results@v2.2.5
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Fail if there were test problems
+        if: steps.process-trx.outputs.test-outcome == 'Failed'
+        run: |
+          echo "There were test failures"
+          exit 1
